use_frameworks!

platform :ios, '8.0'

target 'FSUIKit_Example' do
  pod 'FSUIKit', :path => '../'

  target 'FSUIKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
